# Generated by Django 3.1.7 on 2021-11-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_usuariop2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioP3',
            fields=[
                ('rut', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=300)),
                ('edad', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
