# Generated by Django 3.1.7 on 2021-11-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_usuariop3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioP2',
        ),
    ]
