# Generated by Django 3.2.13 on 2022-05-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar2',
            fields=[
                ('idHora', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.dia')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.hora')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.medico')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.mes')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuariop3')),
            ],
        ),
    ]
