# Generated by Django 3.2.13 on 2022-05-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_agendar4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar5',
            fields=[
                ('idHora', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=300)),
                ('mes', models.CharField(max_length=300)),
                ('hora', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=300)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.medico')),
            ],
        ),
    ]
