# Generated by Django 3.2.13 on 2022-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_agendar6'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioP4',
            fields=[
                ('rut', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=300)),
                ('apellidos', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('provincia', models.CharField(max_length=300)),
                ('comuna', models.CharField(max_length=300)),
                ('edad', models.CharField(max_length=300)),
                ('sexo', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
